name: dsci522-ia2-env
channels:
  - conda-forge
dependencies:
  - python=3.11.9
  - numpy==2.1.3
  - pandas==2.2.3
  - pandera==0.21.0
  - deepchecks==0.3.2
  - matplotlib==3.9.2
  - altair==5.5.0
  - nbconvert==7.16.4
  - seaborn==0.13.2
  - scikit-learn==1.5.2
  - jupyterlab==4.3.1
  - ipykernel==6.29.5
  - xgboost==2.1.2
  - pip==24.3.1
